ktor:
    application:
        modules:
            - com.restaurant.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "http://localhost/"
  audience: "jwt-audience"
  realm: "jwt-realm"
  secret: "rjhitrejh"
db:
  url: "jdbc:postgresql://localhost:5432/restaurant"
  user: "postgres"
  driver: "org.postgresql.Driver"
  password: "postgres"
hash:
  algorithm: "PBKDF2WithHmacSHA512"
  iterations: 100000
  keyLength: 256
  secret: "SomeRandomSecret"